//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1路 21 姚家小区 南关岭 北市集团 东风日产专营店 金色阳光家园 博森石材市场 二十三中学 三道沟 天洋路 千山路 金三角 金三角市场 大纺 亿达世纪城 春柳河 工人村 香炉礁 鞍山路 大连西站 北岗桥 青泥洼桥 
        ///1路加车 12 泉水购物中心 锦泉园 金色阳光家园 阳光家园二期 友好园 三道沟净水厂 三道沟 天洋路 天河路 千山路 金三角 金三角市场 
        ///2路 12 老虎滩 解放路 小龙街 白云街 秀月街 桃源街 青云街 葵英街 中医院 武昌街 劳动公园 青泥洼桥 
        ///3路 20 榆林街 榆水街 榆石街 轻工学院 双欣园 玉水街 水泥厂 泡崖新村 泡崖村 朱棋路 周水子 迎客广场 周水前 刘家桥 春柳 车家村 香工街 沙河口火车站 中长街 兴工街 
        ///4路 16 老虎滩 解放路 小龙街 秀月街 桃源桥 桃源街 八一路 半岛晨报社 南石道街小学 南石道街 北石道街 白云山 高尔基路 奥林匹克广场 民政街 五一广场 
        ///5路 15 森林动物园南门 银沙滩 市委党校 付家庄 三寰大酒店 214医院 仲夏客舍 八一路 群英巷 桃源街 青云街 石葵路 中医院 劳动公园东门 青泥洼桥 
        ///6路 15 甘井子 椒房 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
    }
}
